/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IMorphoInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "borrowBalanceInOf"
      | "borrowRatePerYear"
      | "supply"
      | "supplyBalanceInOf"
      | "supplyRatePerYear"
      | "withdraw"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "borrowBalanceInOf",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "borrowRatePerYear",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supply",
    values: [AddressLike, BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supplyBalanceInOf",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supplyRatePerYear",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BigNumberish, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "borrowBalanceInOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "borrowRatePerYear",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "supply", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supplyBalanceInOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supplyRatePerYear",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export interface IMorpho extends BaseContract {
  connect(runner?: ContractRunner | null): IMorpho;
  waitForDeployment(): Promise<this>;

  interface: IMorphoInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  borrowBalanceInOf: TypedContractMethod<
    [underlying: AddressLike, user: AddressLike],
    [bigint],
    "view"
  >;

  borrowRatePerYear: TypedContractMethod<
    [underlying: AddressLike],
    [bigint],
    "view"
  >;

  supply: TypedContractMethod<
    [
      underlying: AddressLike,
      amount: BigNumberish,
      onBehalfOf: AddressLike,
      maxIterations: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  supplyBalanceInOf: TypedContractMethod<
    [underlying: AddressLike, user: AddressLike],
    [bigint],
    "view"
  >;

  supplyRatePerYear: TypedContractMethod<
    [underlying: AddressLike],
    [bigint],
    "view"
  >;

  withdraw: TypedContractMethod<
    [
      underlying: AddressLike,
      amount: BigNumberish,
      receiver: AddressLike,
      maxIterations: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "borrowBalanceInOf"
  ): TypedContractMethod<
    [underlying: AddressLike, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "borrowRatePerYear"
  ): TypedContractMethod<[underlying: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "supply"
  ): TypedContractMethod<
    [
      underlying: AddressLike,
      amount: BigNumberish,
      onBehalfOf: AddressLike,
      maxIterations: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supplyBalanceInOf"
  ): TypedContractMethod<
    [underlying: AddressLike, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "supplyRatePerYear"
  ): TypedContractMethod<[underlying: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [
      underlying: AddressLike,
      amount: BigNumberish,
      receiver: AddressLike,
      maxIterations: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  filters: {};
}
