/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMorphoToken,
  IMorphoTokenInterface,
} from "../../../../contracts/interfaces/IMorpho.sol/IMorphoToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "underlying",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IMorphoToken__factory {
  static readonly abi = _abi;
  static createInterface(): IMorphoTokenInterface {
    return new Interface(_abi) as IMorphoTokenInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMorphoToken {
    return new Contract(address, _abi, runner) as unknown as IMorphoToken;
  }
}
