/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CompactMultiProtocolVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "aTokens"
      | "aaveAllocations"
      | "aavePool"
      | "accumulatedFees"
      | "authorizedBridges"
      | "calculateNetYield"
      | "calculateYield"
      | "deposit"
      | "feeRecipient"
      | "getAllocations"
      | "getFeeInfo"
      | "getProtocolBalances"
      | "getTokenStats"
      | "getTotalValue"
      | "getUserInfo"
      | "initialize"
      | "lastRecordedValue"
      | "morphoAllocations"
      | "morphoVaults"
      | "owner"
      | "performanceFeeRate"
      | "proxiableUUID"
      | "rebalance"
      | "receiveFromBridge"
      | "redeem"
      | "renounceOwnership"
      | "setAaveConfig"
      | "setBridgeAuthorization"
      | "setFeeRecipient"
      | "setMorphoVault"
      | "setPerformanceFeeRate"
      | "setProtocolAllocations"
      | "setSupportedToken"
      | "supportedTokens"
      | "totalDeposited"
      | "totalFeesWithdrawn"
      | "totalShares"
      | "totalWithdrawn"
      | "transferOwnership"
      | "upgradeToAndCall"
      | "userShares"
      | "withdrawAllFees"
      | "withdrawPerformanceFee"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AllocationSet"
      | "FeeRecipientSet"
      | "Initialized"
      | "OwnershipTransferred"
      | "PerformanceFeeCollected"
      | "PerformanceFeeSet"
      | "PerformanceFeeWithdrawn"
      | "ProtocolDeposit"
      | "SharesMinted"
      | "SharesRedeemed"
      | "TokenSupported"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "aTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "aaveAllocations",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "aavePool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "accumulatedFees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedBridges",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateNetYield",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateYield",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllocations",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeeInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProtocolBalances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalValue",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserInfo",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastRecordedValue",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "morphoAllocations",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "morphoVaults",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "performanceFeeRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rebalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveFromBridge",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "redeem",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAaveConfig",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBridgeAuthorization",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMorphoVault",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPerformanceFeeRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolAllocations",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSupportedToken",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalDeposited",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalFeesWithdrawn",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalShares",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalWithdrawn",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userShares",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAllFees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPerformanceFee",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "aTokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "aaveAllocations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "aavePool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "accumulatedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedBridges",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateNetYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllocations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFeeInfo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProtocolBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastRecordedValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "morphoAllocations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "morphoVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "performanceFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rebalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receiveFromBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAaveConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBridgeAuthorization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMorphoVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPerformanceFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolAllocations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSupportedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalDeposited",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFeesWithdrawn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalWithdrawn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userShares", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAllFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPerformanceFee",
    data: BytesLike
  ): Result;
}

export namespace AllocationSetEvent {
  export type InputTuple = [
    token: AddressLike,
    aavePercentage: BigNumberish,
    morphoPercentage: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    aavePercentage: bigint,
    morphoPercentage: bigint
  ];
  export interface OutputObject {
    token: string;
    aavePercentage: bigint;
    morphoPercentage: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeRecipientSetEvent {
  export type InputTuple = [newRecipient: AddressLike];
  export type OutputTuple = [newRecipient: string];
  export interface OutputObject {
    newRecipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PerformanceFeeCollectedEvent {
  export type InputTuple = [token: AddressLike, feeAmount: BigNumberish];
  export type OutputTuple = [token: string, feeAmount: bigint];
  export interface OutputObject {
    token: string;
    feeAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PerformanceFeeSetEvent {
  export type InputTuple = [newFeeRate: BigNumberish];
  export type OutputTuple = [newFeeRate: bigint];
  export interface OutputObject {
    newFeeRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PerformanceFeeWithdrawnEvent {
  export type InputTuple = [
    token: AddressLike,
    amount: BigNumberish,
    recipient: AddressLike
  ];
  export type OutputTuple = [token: string, amount: bigint, recipient: string];
  export interface OutputObject {
    token: string;
    amount: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolDepositEvent {
  export type InputTuple = [
    token: AddressLike,
    amount: BigNumberish,
    protocol: string
  ];
  export type OutputTuple = [token: string, amount: bigint, protocol: string];
  export interface OutputObject {
    token: string;
    amount: bigint;
    protocol: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesMintedEvent {
  export type InputTuple = [
    user: AddressLike,
    token: AddressLike,
    shares: BigNumberish,
    assets: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    token: string,
    shares: bigint,
    assets: bigint
  ];
  export interface OutputObject {
    user: string;
    token: string;
    shares: bigint;
    assets: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesRedeemedEvent {
  export type InputTuple = [
    user: AddressLike,
    token: AddressLike,
    shares: BigNumberish,
    assets: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    token: string,
    shares: bigint,
    assets: bigint
  ];
  export interface OutputObject {
    user: string;
    token: string;
    shares: bigint;
    assets: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenSupportedEvent {
  export type InputTuple = [token: AddressLike, supported: boolean];
  export type OutputTuple = [token: string, supported: boolean];
  export interface OutputObject {
    token: string;
    supported: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CompactMultiProtocolVault extends BaseContract {
  connect(runner?: ContractRunner | null): CompactMultiProtocolVault;
  waitForDeployment(): Promise<this>;

  interface: CompactMultiProtocolVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  aTokens: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  aaveAllocations: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  aavePool: TypedContractMethod<[], [string], "view">;

  accumulatedFees: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  authorizedBridges: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  calculateNetYield: TypedContractMethod<
    [token: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalValue: bigint;
        principal: bigint;
        grossYield: bigint;
        feeAmount: bigint;
        netYield: bigint;
        netYieldRate: bigint;
      }
    ],
    "view"
  >;

  calculateYield: TypedContractMethod<
    [token: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        totalValue: bigint;
        principal: bigint;
        yieldAmount: bigint;
        yieldRate: bigint;
      }
    ],
    "view"
  >;

  deposit: TypedContractMethod<
    [token: AddressLike, assets: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  getAllocations: TypedContractMethod<
    [token: AddressLike],
    [[bigint, bigint] & { aave: bigint; morpho: bigint }],
    "view"
  >;

  getFeeInfo: TypedContractMethod<
    [token: AddressLike],
    [
      [bigint, bigint, bigint, string] & {
        feeRate: bigint;
        accumulatedFeeAmount: bigint;
        totalFeesWithdrawnAmount: bigint;
        recipient: string;
      }
    ],
    "view"
  >;

  getProtocolBalances: TypedContractMethod<
    [token: AddressLike],
    [
      [bigint, bigint, bigint] & {
        aaveBalance: bigint;
        morphoBalance: bigint;
        totalBalance: bigint;
      }
    ],
    "view"
  >;

  getTokenStats: TypedContractMethod<
    [token: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        deposited: bigint;
        withdrawn: bigint;
        totalSharesSupply: bigint;
        currentValue: bigint;
      }
    ],
    "view"
  >;

  getTotalValue: TypedContractMethod<[token: AddressLike], [bigint], "view">;

  getUserInfo: TypedContractMethod<
    [user: AddressLike, token: AddressLike],
    [
      [bigint, bigint, bigint] & {
        shares: bigint;
        assets: bigint;
        shareValue: bigint;
      }
    ],
    "view"
  >;

  initialize: TypedContractMethod<[_owner: AddressLike], [void], "nonpayable">;

  lastRecordedValue: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  morphoAllocations: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  morphoVaults: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  performanceFeeRate: TypedContractMethod<[], [bigint], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  rebalance: TypedContractMethod<[token: AddressLike], [void], "nonpayable">;

  receiveFromBridge: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  redeem: TypedContractMethod<
    [token: AddressLike, shares: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAaveConfig: TypedContractMethod<
    [_aavePool: AddressLike, token: AddressLike, aToken: AddressLike],
    [void],
    "nonpayable"
  >;

  setBridgeAuthorization: TypedContractMethod<
    [bridge: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  setFeeRecipient: TypedContractMethod<
    [_feeRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  setMorphoVault: TypedContractMethod<
    [token: AddressLike, vault: AddressLike],
    [void],
    "nonpayable"
  >;

  setPerformanceFeeRate: TypedContractMethod<
    [_feeRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  setProtocolAllocations: TypedContractMethod<
    [
      token: AddressLike,
      aavePercentage: BigNumberish,
      morphoPercentage: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setSupportedToken: TypedContractMethod<
    [token: AddressLike, supported: boolean],
    [void],
    "nonpayable"
  >;

  supportedTokens: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  totalDeposited: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  totalFeesWithdrawn: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  totalShares: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  totalWithdrawn: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  userShares: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  withdrawAllFees: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawPerformanceFee: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "aTokens"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "aaveAllocations"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "aavePool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "accumulatedFees"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "authorizedBridges"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "calculateNetYield"
  ): TypedContractMethod<
    [token: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalValue: bigint;
        principal: bigint;
        grossYield: bigint;
        feeAmount: bigint;
        netYield: bigint;
        netYieldRate: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateYield"
  ): TypedContractMethod<
    [token: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        totalValue: bigint;
        principal: bigint;
        yieldAmount: bigint;
        yieldRate: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [token: AddressLike, assets: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAllocations"
  ): TypedContractMethod<
    [token: AddressLike],
    [[bigint, bigint] & { aave: bigint; morpho: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFeeInfo"
  ): TypedContractMethod<
    [token: AddressLike],
    [
      [bigint, bigint, bigint, string] & {
        feeRate: bigint;
        accumulatedFeeAmount: bigint;
        totalFeesWithdrawnAmount: bigint;
        recipient: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProtocolBalances"
  ): TypedContractMethod<
    [token: AddressLike],
    [
      [bigint, bigint, bigint] & {
        aaveBalance: bigint;
        morphoBalance: bigint;
        totalBalance: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenStats"
  ): TypedContractMethod<
    [token: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        deposited: bigint;
        withdrawn: bigint;
        totalSharesSupply: bigint;
        currentValue: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalValue"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserInfo"
  ): TypedContractMethod<
    [user: AddressLike, token: AddressLike],
    [
      [bigint, bigint, bigint] & {
        shares: bigint;
        assets: bigint;
        shareValue: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[_owner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "lastRecordedValue"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "morphoAllocations"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "morphoVaults"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "performanceFeeRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rebalance"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "receiveFromBridge"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "redeem"
  ): TypedContractMethod<
    [token: AddressLike, shares: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAaveConfig"
  ): TypedContractMethod<
    [_aavePool: AddressLike, token: AddressLike, aToken: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBridgeAuthorization"
  ): TypedContractMethod<
    [bridge: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFeeRecipient"
  ): TypedContractMethod<[_feeRecipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMorphoVault"
  ): TypedContractMethod<
    [token: AddressLike, vault: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPerformanceFeeRate"
  ): TypedContractMethod<[_feeRate: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setProtocolAllocations"
  ): TypedContractMethod<
    [
      token: AddressLike,
      aavePercentage: BigNumberish,
      morphoPercentage: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSupportedToken"
  ): TypedContractMethod<
    [token: AddressLike, supported: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportedTokens"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalDeposited"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalFeesWithdrawn"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalShares"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalWithdrawn"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "userShares"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawAllFees"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawPerformanceFee"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AllocationSet"
  ): TypedContractEvent<
    AllocationSetEvent.InputTuple,
    AllocationSetEvent.OutputTuple,
    AllocationSetEvent.OutputObject
  >;
  getEvent(
    key: "FeeRecipientSet"
  ): TypedContractEvent<
    FeeRecipientSetEvent.InputTuple,
    FeeRecipientSetEvent.OutputTuple,
    FeeRecipientSetEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PerformanceFeeCollected"
  ): TypedContractEvent<
    PerformanceFeeCollectedEvent.InputTuple,
    PerformanceFeeCollectedEvent.OutputTuple,
    PerformanceFeeCollectedEvent.OutputObject
  >;
  getEvent(
    key: "PerformanceFeeSet"
  ): TypedContractEvent<
    PerformanceFeeSetEvent.InputTuple,
    PerformanceFeeSetEvent.OutputTuple,
    PerformanceFeeSetEvent.OutputObject
  >;
  getEvent(
    key: "PerformanceFeeWithdrawn"
  ): TypedContractEvent<
    PerformanceFeeWithdrawnEvent.InputTuple,
    PerformanceFeeWithdrawnEvent.OutputTuple,
    PerformanceFeeWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolDeposit"
  ): TypedContractEvent<
    ProtocolDepositEvent.InputTuple,
    ProtocolDepositEvent.OutputTuple,
    ProtocolDepositEvent.OutputObject
  >;
  getEvent(
    key: "SharesMinted"
  ): TypedContractEvent<
    SharesMintedEvent.InputTuple,
    SharesMintedEvent.OutputTuple,
    SharesMintedEvent.OutputObject
  >;
  getEvent(
    key: "SharesRedeemed"
  ): TypedContractEvent<
    SharesRedeemedEvent.InputTuple,
    SharesRedeemedEvent.OutputTuple,
    SharesRedeemedEvent.OutputObject
  >;
  getEvent(
    key: "TokenSupported"
  ): TypedContractEvent<
    TokenSupportedEvent.InputTuple,
    TokenSupportedEvent.OutputTuple,
    TokenSupportedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "AllocationSet(address,uint256,uint256)": TypedContractEvent<
      AllocationSetEvent.InputTuple,
      AllocationSetEvent.OutputTuple,
      AllocationSetEvent.OutputObject
    >;
    AllocationSet: TypedContractEvent<
      AllocationSetEvent.InputTuple,
      AllocationSetEvent.OutputTuple,
      AllocationSetEvent.OutputObject
    >;

    "FeeRecipientSet(address)": TypedContractEvent<
      FeeRecipientSetEvent.InputTuple,
      FeeRecipientSetEvent.OutputTuple,
      FeeRecipientSetEvent.OutputObject
    >;
    FeeRecipientSet: TypedContractEvent<
      FeeRecipientSetEvent.InputTuple,
      FeeRecipientSetEvent.OutputTuple,
      FeeRecipientSetEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PerformanceFeeCollected(address,uint256)": TypedContractEvent<
      PerformanceFeeCollectedEvent.InputTuple,
      PerformanceFeeCollectedEvent.OutputTuple,
      PerformanceFeeCollectedEvent.OutputObject
    >;
    PerformanceFeeCollected: TypedContractEvent<
      PerformanceFeeCollectedEvent.InputTuple,
      PerformanceFeeCollectedEvent.OutputTuple,
      PerformanceFeeCollectedEvent.OutputObject
    >;

    "PerformanceFeeSet(uint256)": TypedContractEvent<
      PerformanceFeeSetEvent.InputTuple,
      PerformanceFeeSetEvent.OutputTuple,
      PerformanceFeeSetEvent.OutputObject
    >;
    PerformanceFeeSet: TypedContractEvent<
      PerformanceFeeSetEvent.InputTuple,
      PerformanceFeeSetEvent.OutputTuple,
      PerformanceFeeSetEvent.OutputObject
    >;

    "PerformanceFeeWithdrawn(address,uint256,address)": TypedContractEvent<
      PerformanceFeeWithdrawnEvent.InputTuple,
      PerformanceFeeWithdrawnEvent.OutputTuple,
      PerformanceFeeWithdrawnEvent.OutputObject
    >;
    PerformanceFeeWithdrawn: TypedContractEvent<
      PerformanceFeeWithdrawnEvent.InputTuple,
      PerformanceFeeWithdrawnEvent.OutputTuple,
      PerformanceFeeWithdrawnEvent.OutputObject
    >;

    "ProtocolDeposit(address,uint256,string)": TypedContractEvent<
      ProtocolDepositEvent.InputTuple,
      ProtocolDepositEvent.OutputTuple,
      ProtocolDepositEvent.OutputObject
    >;
    ProtocolDeposit: TypedContractEvent<
      ProtocolDepositEvent.InputTuple,
      ProtocolDepositEvent.OutputTuple,
      ProtocolDepositEvent.OutputObject
    >;

    "SharesMinted(address,address,uint256,uint256)": TypedContractEvent<
      SharesMintedEvent.InputTuple,
      SharesMintedEvent.OutputTuple,
      SharesMintedEvent.OutputObject
    >;
    SharesMinted: TypedContractEvent<
      SharesMintedEvent.InputTuple,
      SharesMintedEvent.OutputTuple,
      SharesMintedEvent.OutputObject
    >;

    "SharesRedeemed(address,address,uint256,uint256)": TypedContractEvent<
      SharesRedeemedEvent.InputTuple,
      SharesRedeemedEvent.OutputTuple,
      SharesRedeemedEvent.OutputObject
    >;
    SharesRedeemed: TypedContractEvent<
      SharesRedeemedEvent.InputTuple,
      SharesRedeemedEvent.OutputTuple,
      SharesRedeemedEvent.OutputObject
    >;

    "TokenSupported(address,bool)": TypedContractEvent<
      TokenSupportedEvent.InputTuple,
      TokenSupportedEvent.OutputTuple,
      TokenSupportedEvent.OutputObject
    >;
    TokenSupported: TypedContractEvent<
      TokenSupportedEvent.InputTuple,
      TokenSupportedEvent.OutputTuple,
      TokenSupportedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
